
// Automatically generated configuration file.

# ifndef __MBED_CONFIG_DATA__
# define __MBED_CONFIG_DATA__

// Configuration parameters

#if !defined(MBED_CONF_PLATFORM_STDIO_BAUD_RATE)
	#define MBED_CONF_PLATFORM_STDIO_BAUD_RATE (9600)
#endif
#if !defined(MBED_CONF_LWIP_IPV6_ENABLED)
	#define MBED_CONF_LWIP_IPV6_ENABLED (0)
#endif
#if !defined(STM32_D11_SPI_ETHERNET_PIN)
	#define STM32_D11_SPI_ETHERNET_PIN (PA_7)
#endif
#if !defined(MBED_CONF_LWIP_UDP_SOCKET_MAX)
	#define MBED_CONF_LWIP_UDP_SOCKET_MAX (4)
#endif
#if !defined(MBED_CONF_LWIP_IP_VER_PREF)
	#define MBED_CONF_LWIP_IP_VER_PREF (4)
#endif
#if !defined(MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE)
	#define MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE (256)
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES)
	#define MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES (0)
#endif
#if !defined(MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE)
	#define MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE (9600)
#endif
#if !defined(MBED_CONF_LWIP_ENABLE_PPP_TRACE)
	#define MBED_CONF_LWIP_ENABLE_PPP_TRACE (0)
#endif
#if !defined(MBED_CONF_LWIP_DEBUG_ENABLED)
	#define MBED_CONF_LWIP_DEBUG_ENABLED (0)
#endif
#if !defined(MBED_CONF_LWIP_PPP_THREAD_STACKSIZE)
	#define MBED_CONF_LWIP_PPP_THREAD_STACKSIZE (768)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP)
	#define MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP (0)
#endif
#if !defined(MBED_CONF_LWIP_TCP_ENABLED)
	#define MBED_CONF_LWIP_TCP_ENABLED (1)
#endif
#if !defined(MBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE)
	#define MBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE (256)
#endif
#if !defined(CLOCK_SOURCE)
	#define CLOCK_SOURCE (USE_PLL_HSE_EXTC|USE_PLL_HSE_XTAL|USE_PLL_HSI)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT)
	#define MBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT (8000)
#endif
#if !defined(MBED_CONF_LWIP_TCP_SOCKET_MAX)
	#define MBED_CONF_LWIP_TCP_SOCKET_MAX (4)
#endif
#if !defined(MBED_CONF_LWIP_DEFAULT_THREAD_STACKSIZE)
	#define MBED_CONF_LWIP_DEFAULT_THREAD_STACKSIZE (512)
#endif
#if !defined(MBED_CONF_LWIP_TCPIP_THREAD_STACKSIZE)
	#define MBED_CONF_LWIP_TCPIP_THREAD_STACKSIZE (1200)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_BAUD_RATE)
	#define MBED_CONF_PPP_CELL_IFACE_BAUD_RATE (115200)
#endif
#if !defined(MBED_CONF_LWIP_SOCKET_MAX)
	#define MBED_CONF_LWIP_SOCKET_MAX (4)
#endif
#if !defined(NSAPI_PPP_AVAILABLE)
	#define NSAPI_PPP_AVAILABLE (0)
#endif
#if !defined(MBED_CONF_LWIP_TCP_SERVER_MAX)
	#define MBED_CONF_LWIP_TCP_SERVER_MAX (4)
#endif
#if !defined(MBED_CONF_LWIP_ADDR_TIMEOUT)
	#define MBED_CONF_LWIP_ADDR_TIMEOUT (5)
#endif
#if !defined(MBED_CONF_LWIP_ETHERNET_ENABLED)
	#define MBED_CONF_LWIP_ETHERNET_ENABLED (1)
#endif
#if !defined(MBED_CONF_LWIP_IPV4_ENABLED)
	#define MBED_CONF_LWIP_IPV4_ENABLED (1)
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT)
	#define MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT (1)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE)
	#define MBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE (256)
#endif
#if !defined(MBED_CONF_LWIP_USE_MBED_TRACE)
	#define MBED_CONF_LWIP_USE_MBED_TRACE (0)
#endif
#if !defined(UNITY_INCLUDE_CONFIG_H)
	#define UNITY_INCLUDE_CONFIG_H
#endif


# endif
