
// Automatically generated configuration file.

# ifndef __MBED_CONFIG_DATA__
# define __MBED_CONFIG_DATA__

// Configuration parameters

#if !defined(LFXO_FREQUENCY)
	#define LFXO_FREQUENCY (32768)
#endif
#if !defined(MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE)
	#define MBED_CONF_PLATFORM_DEFAULT_SERIAL_BAUD_RATE (9600)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP)
	#define MBED_CONF_PPP_CELL_IFACE_APN_LOOKUP (0)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE)
	#define MBED_CONF_PPP_CELL_IFACE_AT_PARSER_BUFFER_SIZE (256)
#endif
#if !defined(MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE)
	#define MBED_CONF_DRIVERS_UART_SERIAL_RXBUF_SIZE (256)
#endif
#if !defined(LOW_ENERGY_CLOCK_SOURCE)
	#define LOW_ENERGY_CLOCK_SOURCE (LFXO)
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_BAUD_RATE)
	#define MBED_CONF_PLATFORM_STDIO_BAUD_RATE (115200)
#endif
#if !defined(HFXO_FREQUENCY)
	#define HFXO_FREQUENCY (40000000)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT)
	#define MBED_CONF_PPP_CELL_IFACE_AT_PARSER_TIMEOUT (8000)
#endif
#if !defined(CORE_CLOCK_SOURCE)
	#define CORE_CLOCK_SOURCE (HFXO)
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES)
	#define MBED_CONF_PLATFORM_STDIO_CONVERT_NEWLINES (0)
#endif
#if !defined(EFM_BC_EN)
	#define EFM_BC_EN (PA5)
#endif
#if !defined(MBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE)
	#define MBED_CONF_DRIVERS_UART_SERIAL_TXBUF_SIZE (256)
#endif
#if !defined(MBED_CONF_PPP_CELL_IFACE_BAUD_RATE)
	#define MBED_CONF_PPP_CELL_IFACE_BAUD_RATE (115200)
#endif
#if !defined(HFRCO_FREQUENCY)
	#define HFRCO_FREQUENCY (32000000)
#endif
#if !defined(HFRCO_FREQUENCY_ENUM)
	#define HFRCO_FREQUENCY_ENUM (cmuHFRCOFreq_32M0Hz)
#endif
#if !defined(MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT)
	#define MBED_CONF_PLATFORM_STDIO_FLUSH_AT_EXIT (1)
#endif
#if !defined(UNITY_INCLUDE_CONFIG_H)
	#define UNITY_INCLUDE_CONFIG_H
#endif


# endif
